name: CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install

      - name: Set up db
        run: cd packages/backend && pnpm db:push

      - name: Create .env file for local DB
        run: |
          echo "DATABASE_URL=postgres://postgres:postgres@localhost:5432/testdb" > packages/backend/.env
          echo "DATABASE_URL=postgres://postgres:postgres@localhost:5432/testdb" > packages/backend/.env.test

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 1
          done

      - name: Run tests
        run: pnpm test
