name: CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install

      - name: Create .env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > packages/backend/.env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > packages/backend/.env.test
      
      - name: Run tests
        run: pnpm test
